---
- hosts: rtv_adc01
  connection: local
  become: true
  vars:
    # -- Custom settings: role-samba4-primary-ad-dc --
    smb_workgroup : 'RTVCHALLENGE'
    smb_realm     : 'RTVCHALLENGE.NET' 
    smb_username  : 'administrator'
    smb_password  : 'X3E5Op3RH1US4ok5'
  roles:
    - role-samba4-primary-ad-dc
